---
- name: Add Registry Keys on Windows Server
  hosts: all
  gather_facts: false
  vars_files:
    - vars/service_vars.yaml  
  tasks:
    - name: Create a new registry key
      loop: "{{ firewall_rules_inbound }}"
      ansible.windows.win_regedit:
        path: "{{ item.path }}"
        name: "{{ item.name }}"
        type: "{{ item.type }}"
        data: "{{ item.data }}"
        state: "{{ item.state }}"