---
- name: Set Local Group Policy on Windows Server
  hosts: all
  gather_facts: false
  vars_files:
    - vars/service_vars.yaml  
  tasks:
    - name: Set minimum password length
      loop: "{{ change_policy }}"
      ansible.windows.win_shell: |
        Import-Module -Name "CimCmdlets"
        $Path = "{{ item.path }}"
        Set-ItemProperty -Path $Path -Name "{{ item.name }}" -Value "{{ item.value }}"