---
- name: Install PostgreSQL
  hosts: all
  become: true
  vars_files:
    - vars/service_vars.yaml  
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: "Install packages"
      apt: 
        name: "postgresql-{{ postgre_db.version }}"
        state: present

    - name: Install pip if not installed
      apt:
        name: python3-pip
        state: present

    - name: "Install Python packages"
      pip: "name={{ postgre_db.init_db_lib }}  state=present"

  tasks:
    - name: Initialize PostgreSQL
      shell: initdb -D /var/lib/postgresql/{{ postgre_db.version }}/main
      args:
        creates: /var/lib/postgresql/14/main/PG_VERSION  # Chỉ chạy nếu tệp này không tồn tại

  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted