---
- name: Update Windows Server
  hosts: all
  gather_facts: false
  vars_files:
    - vars/service_vars.yaml  
  tasks:
    - name: Scan for available updates
      ansible.windows.win_updates:
        category_names: "{{ window_update.category_names }}"
        state: searched
      register: available_update

    - name: Print available update
      debug:
        var: available_update  