---
- name: Manage Windows Service
  hosts: all
  vars_files:
    - vars/service_vars.yaml
  tasks:
    - name: Get the status of the services
      loop: "{{ service_list }}"
      loop_control:
        loop_var: item
      ansible.windows.win_service_info:
        name: "{{ item }}"
      register: service_info

    - name: Debug service info (optional, for checking purposes)
      debug:
        var: service_info.results

    - name: If any service is stopped, then start it
      loop: "{{ service_info.results }}"
      loop_control:
        loop_var: item    
      when: item.services[0].state == 'stopped'
      ansible.windows.win_service:
        name: "{{ item.item }}"
        state: started

    - name: Get the status of the services after start
      loop: "{{ service_list }}"
      loop_control:
        loop_var: item    
      ansible.windows.win_service_info:
        name: "{{ item }}"
      register: service_info_after

    - name: Debug service info after start (optional, for checking purposes)
      debug:
        var: service_info_after.results