---
- name: Manage Windows Service
  hosts: all
  vars_files:
    - service_vars.yml
  tasks:
    - name: Get the status of the service "{{ service_name }}"
      ansible.windows.win_service_info:
        name: "{{ service_name }}"
      register: service_info

    - name: Debug service info (optional, for checking purposes)
      debug:
        var: service_info

    - name: If the service is stopped then started
      ansible.windows.win_service:
        name: "{{ service_name }}"
        state: started
      when: service_info.services[0].state == 'stopped'

    - name: Get the status of the service "{{ service_name }}" after start
      ansible.windows.win_service_info:
        name: "{{ service_name }}"
      register: service_info_after
      
    - name: Debug service info (optional, for checking purposes)
      debug:
        var: service_info_after
