---
- name: Manage Windows Service
  hosts: all
  tasks:
    - name: Get the status of the service CaptureService_17b059c9
      ansible.windows.win_service_info:
        name: "CaptureService_17b059c9"
      register: service_info

    - name: Debug service info (optional, for checking purposes)
      debug:
        var: service_info

    - name: Ensure the service is running before continuing
      ansible.windows.win_service:
        name: "CaptureService_17b059c9"
        state: started
      when: service_info.services.state == 'stopped'

    - name: Get the status of the service CaptureService_17b059c9 after start
      ansible.windows.win_service_info:
        name: "CaptureService_17b059c9"
      register: service_info_after
      
    - name: Debug service info (optional, for checking purposes)
      debug:
        var: service_info_after
