---
- name: Update Windows Server
  hosts: all
  gather_facts: false
  vars_files:
    - vars/service_vars.yaml  
  tasks:
    - name: Scan for available updates
      ansible.windows.win_updates:
        category_names: "{{ window_update.category_names }}"
        state: searched
      register: available_update

    - name: Print available update
      debug:
        var: available_update  

    - name: Install all available updates
      when: available_update.updates | length > 0
      ansible.windows.win_updates:
        category_names: "{{ window_update.category_names }}"
        state: installed
        reboot: true

    - name: Wait before rebooting
      when: window_update.reboot == true
      ansible.builtin.pause:
        minutes: "{{ window_update.wait_time_before_reboot.minutes }}"  # minutes
      
    - name: Reboot if choose
      when: window_update.reboot == true
      ansible.windows.win_reboot:
        reboot_timeout: 3600

