---
- name: Update Windows Server
  hosts: all
  gather_facts: false
  vars_files:
    - vars/service_vars.yaml  
  tasks:
    - name: Install all available updates
      ansible.windows.win_updates:
        category_names: "{{ window_update.category_names }}"
        state: installed

    - name: Wait before rebooting
      when: window_update.reboot == true
      ansible.builtin.pause:
        minutes: "{{ window_update.wait_time_before_reboot.minutes }}"  # minutes
      
    - name: Reboot if choose
      when: window_update.reboot == true
      ansible.windows.win_reboot:
        reboot_timeout: 3600

